// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTlZxdA8_MeKktQvOMRfjBvqUgy1G-jCU',
    appId: '1:1000218100414:web:55cdee57b6f9aca99c94ef',
    messagingSenderId: '1000218100414',
    projectId: 'fir-work-d4e7d',
    authDomain: 'fir-work-d4e7d.firebaseapp.com',
    storageBucket: 'fir-work-d4e7d.appspot.com',
    measurementId: 'G-F8FCQLCX4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuNrR4pZtKw4SOqW9qqs1g8akUDnhcuEI',
    appId: '1:1000218100414:android:b12b28f32f82747f9c94ef',
    messagingSenderId: '1000218100414',
    projectId: 'fir-work-d4e7d',
    storageBucket: 'fir-work-d4e7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf8Z5d0Zt5xKrMuGeSIYVL1_Q9lsJT5NM',
    appId: '1:1000218100414:ios:b51b8f2731e248a49c94ef',
    messagingSenderId: '1000218100414',
    projectId: 'fir-work-d4e7d',
    storageBucket: 'fir-work-d4e7d.appspot.com',
    iosBundleId: 'com.example.work',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf8Z5d0Zt5xKrMuGeSIYVL1_Q9lsJT5NM',
    appId: '1:1000218100414:ios:f9c37d00ee42751b9c94ef',
    messagingSenderId: '1000218100414',
    projectId: 'fir-work-d4e7d',
    storageBucket: 'fir-work-d4e7d.appspot.com',
    iosBundleId: 'com.example.work.RunnerTests',
  );
}
